# TRAINING 
split_idx: 0 # Use 0-indexing for splits: 0 = V/K-01 used as queries, etc.
num_gpus: 1
seed: 2024 

max_epochs: 40
warmup_epochs: 10
milestones: [10,20]
lr: 0.0001
lr_mul: 0.1
weight_decay: 0.0001
loss: multi_similarity_loss

# DATA
wildcross_path: ''
data_folder: images_shrunk
pos_include_radius: 5.0
pos_exclude_radius: 0.0
fov_include_radius: 10.0

train_img_size: [320, 320]
val_img_size: [320, 320]

img_per_place: 4
batch_size: 64
num_workers: 32
anchor_framerate_downsample: 5

# MODEL 
model_name: NetVLAD
descriptor_dimension: 4096
